name: Billboard
version: 1.0.3
author: Garsooon
main: org.garsooon.billboard.billboard
softdepend: [Essentials, Fundamentals, ZCore]

commands:
  buyad:
    description: Request an ad slot
    usage: /<command> <duration_minutes> <message>
  reviewads:
    description: Review pending ads
    permission: billboard.moderate
  approvead:
    description: Approve an ad
    permission: billboard.moderate
  denyad:
    description: Deny an ad
    permission: billboard.moderate
  listads:
    description: List active ads
    permission: billboard.moderate
  broadcast:
    description: Manage server broadcasts
    usage: /<command> <list|add|remove|reload>
    permission: billboard.broadcasts

permissions:
  billboard.moderate:
    description: Allows moderating ads
    default: op
  billboard.broadcasts:
    description: Allows managing server broadcasts in-game
    default: op